export enum Role {
    ACADEMIC_REGISTRY = "ACADEMIC_REGISTRY",
    ACADEMIC_TUTOR = "ACADEMIC_TUTOR",
    NOMINAL_TUTOR = "NOMINAL_TUTOR",
    STUDENT = "STUDENT",
    INNER_AUDITOR = "INNER_AUDITOR",
    OUTER_AUDITOR = "OUTER_AUDITOR",
    DEFENCE_GROUP_TEACHER = "DEFENCE_GROUP_TEACHER"
}